/*
 * Auto-generated by Frida. Please modify to match the signature of _ZeqRK7QStringS1_.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: http://www.frida.re/docs/javascript-api/
 */

{
  /**
   * Called synchronously when about to call _ZeqRK7QStringS1_.
   *
   * @this {object} - Object allowing you to store state for use in onLeave.
   * @param {function} log - Call this function with a string to be presented to the user.
   * @param {array} args - Function arguments represented as an array of NativePointer objects.
   * For example use args[0].readUtf8String() if the first argument is a pointer to a C string encoded as UTF-8.
   * It is also possible to modify arguments by assigning a NativePointer object to an element of this array.
   * @param {object} state - Object allowing you to keep state across function calls.
   * Only one JavaScript function will execute at a time, so do not worry about race-conditions.
   * However, do not use this to store function arguments across onEnter/onLeave, but instead
   * use "this" which is an object for keeping state local to an invocation.
   */
  onEnter: function (log, args, state) {
	var fn_addr = Module.getExportByName('libqt_helper_lib.so.1.0.0', 'qstringp_to_cstr')
	//log('fn_addr:'+fn_addr)
	var fn = new NativeFunction(fn_addr, 'pointer', ['pointer']);
	//log('fn:'+fn)
	var str0 = fn(args[0]).readUtf8String()
	var str1 = fn(args[1]).readUtf8String()
	log('TEST:operator==(QString, QString) "'+str0+'" == "'+str1+'"')
  },

  /**
   * Called synchronously when about to return from _ZeqRK7QStringS1_.
   *
   * See onEnter for details.
   *
   * @this {object} - Object allowing you to access state stored in onEnter.
   * @param {function} log - Call this function with a string to be presented to the user.
   * @param {NativePointer} retval - Return value represented as a NativePointer object.
   * @param {object} state - Object allowing you to keep state across function calls.
   */
  onLeave: function (log, retval, state) {
  	log('  res:'+retval)
  }
}
